### ISSUE TITLE
指定ip地址

### ISSUE THREAD

**Issue by AdministratorGithub** [su18/JNDI#2]

**Comment by AdministratorGithub** [comment]
![image](https://user-images.githubusercontent.com/19834937/85367659-43f57580-b55c-11ea-9e7d-17120c79b42e.png)
ip地址获取有问题

**Comment by AdministratorGithub** [comment]
腾讯云或者其他vps，优先获取内网地址

**Comment by su18** [comment]
默认获取第一个网卡地址，现在改为默认获取第一个外网地址，如果没有外网地址则使用内网地址。
https://github.com/su18/JNDI/commit/1fe22544dc9affc8825e68f4e5eb119566e25fed
可以在配置文件中手动指定IP地址的

**Comment by AdministratorGithub** [comment]
老哥 6
